services:
  goodsdesignapi:
    image: ${DOCKER_REGISTRY-}goodsdesignapi
    build:
      context: .
      dockerfile: GoodsDesignAPI/Dockerfile
    container_name: goodsdesignapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DefaultConnection=Host=goodsdesignapi-database;Port=5432;Database=goodsdesignapi;Username=postgres;Password=YourStrong!Passw0rd;"
      - "JWT__SecretKey=GoodsDesign_SECRETKEY_SIEUCAPBAOMAT_VAYMACHUADU16KYTU"
      - "JWT__Issuer=GoodsDesign_Issuer"
      - "JWT__Audience=GoodsDesign_Audience"
      - "Minio__AccessKey=CX2A6aRmIQxH4rrDmL8S"
      - "Minio__SecretKey=TlP25JEHKQESROCMvXQnEpTzfhhpqNltHokV2ODK"
    ports:
      - "9000:8080"
    depends_on:
      - goodsdesignapi-database

  goodsdesignapi-database:
      image: postgres:latest
      container_name: goodsdesignapi-database
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: YourStrong!Passw0rd
        POSTGRES_DB: goodsdesignapi
      ports:
        - "9432:5432"
      volumes:
        - ./.containers/goodsdesignapi-database-data:/var/lib/postgresql/data

  # goodsdesignapi-unittest:
  #   build:
  #     context: .
  #     dockerfile: UnitTest/Dockerfile
  #   container_name: unit-tests
  #   depends_on:
  #     - goodsdesignapi
  #     - goodsdesignapi-database
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   entrypoint: ["dotnet", "test", "--no-build", "--verbosity", "normal"]  