services:
  # api:
  #   build: .
  #   container_name: goodsdesign-api
  #   restart: always
  #   ports:
  #     - "5000:5000"
  #   env_file:
  #     - .env.production.local
  #   depends_on:
  #     - goodsdesign-db
  #     - redis

  goodsdesign-db:
    container_name: goodsdesign-db
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_DB=goodsdesign_db
      - POSTGRES_USER=goodsdesign_user
      - POSTGRES_PASSWORD=goodsdesign_password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    container_name: goodsdesign-redis
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'

  redisinsight:
    container_name: goodsdesign-redisinsight
    image: redis/redisinsight:latest
    restart: always
    ports:
      - '5540:5540'

volumes:
  postgres:

