-- AlterTable
ALTER TABLE "SystemConfigOrder" ADD COLUMN     "capacityScoreWeight" DOUBLE PRECISION NOT NULL DEFAULT 0.2,
ADD COLUMN     "leadTimeScoreWeight" DOUBLE PRECISION NOT NULL DEFAULT 0.15,
ADD COLUMN     "legitPointScoreWeight" DOUBLE PRECISION NOT NULL DEFAULT 0.25,
ADD COLUMN     "maxLegitPoint" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "maxProductionCapacity" INTEGER NOT NULL DEFAULT 1000,
ADD COLUMN     "maxProductionTimeInMinutes" INTEGER NOT NULL DEFAULT 300,
ADD COLUMN     "operationalHoursScoreWeight" DOUBLE PRECISION NOT NULL DEFAULT 0.15,
ADD COLUMN     "productionCapacityScoreWeight" DOUBLE PRECISION NOT NULL DEFAULT 0.1,
ADD COLUMN     "specializationScoreWeight" DOUBLE PRECISION NOT NULL DEFAULT 0.15;
